### ISSUE TITLE
manager newsletter

### ISSUE THREAD

**Issue by ideesimple** [censusbv/DitsNews#1]
Hi, i install your package.
the tables are create.

the page manager is blank and no error in console log.

**Comment by censusbv** [comment]
Can't reproduce.

**Comment by ideesimple** [comment]
i found why.

it was a permission file on OVH.

now work fine.

Laurent

**Comment by mobe-zz-us** [comment]
I am having the same problem, the manager page appears blank apart from the heading Newsletter.

On IE there is a JS error that mentions this.proxy. I am on revolution 2.0.8 after upgrading from 2.0.7 in an effort to make it work.
PHP 5.2.16
Mysql 5.0.91

what were the file permission that had to be changed?

thanks

J

**Comment by ideesimple** [comment]
i had all my file with 755 for to be sure :-) and work now 
all your file in your folder /assets/component/distsnews/

**Comment by mobe-zz-us** [comment]
Hi , Thanks for the help,

The permissions on the folders within the assets/components/ditsnews folder have  permissions of 0755 but for some reason I can't get the files themselves to have the same permissions,they are currently 0644.

The other components in the dir such as discuss have the same permission structure  and work as dits news currently has when its not working.

how can I change the permissions on the files, I keep getting a message that i don;t have permission to do so?

thanks

J

**Comment by ideesimple** [comment]
via ftp or via the manager file
