### ISSUE TITLE
localhost links in manager

### ISSUE THREAD

**Issue by flayfl** [censusbv/DitsNews#4]
working on localhost, menu on the right is redirecting using absolute path.
check ditsnews.js lines 22,29,36,43.
i had to change '/manager/?a...' to '?a..'
Cheers,
Flavius

**Comment by wdeleeuw** [comment]
Encountered the same problem while not running modx in the webroot. I used index.php?a... to solve it

**Comment by censusbv** [comment]
Won't be a problem in the next release anymore
