### ISSUE TITLE
Manager access

### ISSUE THREAD

**Issue by mobe-zz-us** [censusbv/DitsNews#6]
Hi,

I am still having issues with access to the dits news admin functionality in the manager,

I have tried changing the file permissions as suggested by another user but that still hasn;t fixed the issue for me.

i still get a blank page, how can I fix this?

thanks

**Comment by exside** [comment]
Which version of Revo do you use? I had this white-page problem too and it went away with 2.0.8pl (2.1rc3 has some other issues with this component --> tables not created...)

**Comment by censusbv** [comment]
Can't reproduce. Please, let us know if the problem is still there in the soon to be released next version.

**Comment by exside** [comment]
which problem can't you reproduce? White Page or tables not created?

**Comment by censusbv** [comment]
White page (this Issue is about the white page problem).

**Comment by mobe-zz-us** [comment]
Hi, yes  I have recently upgraded 2.1.1 and I am still having the white page issue in the manager pages.

**Comment by exside** [comment]
Upgrade didn't help as I had this problem...just a clean new installation^^...
