### ISSUE TITLE
redirect path doesn't match .. 

### ISSUE THREAD

**Issue by spezi** [censusbv/DitsNews#8]
i have a similar issue like #4 in the frontend -- my modx runs in a subfolder http://domain.com/subfolder/ 
after klicking subscribe it redirect to http://domain.com/ without the subfolder ..

**Comment by censusbv** [comment]
We are working on a new release. Will be fixed in there.

**Comment by spezi** [comment]
thanks for the fast answer .. do you now a circa release date ?? 

greetings Peter

**Comment by censusbv** [comment]
Should be fixed in 0.2.0 alpha 1
